# fly.toml app configuration file generated for mimeografo-api on 2023-07-30T15:52:45-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mimeografo-api"
primary_region = "gru"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
