name: fly deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    condition:
      - github.event.pull_request.merged == true

jobs:
  deploy_frontend:
    name: deploy frontend
    runs-on: ubuntu-latest
    steps:
      - name: determine current directory
        id: dir
        run: echo "directory=$(pwd)" >> "$GITHUB_OUTPUT"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Deploy frontend
        if: ${{ steps.dir.outputs.directory }}/frontend
        run: |
          cd "${{ steps.dir.outputs.directory }}/frontend"
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

