name: fly deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    condition:
      - github.event.pull_request.merged == true

jobs:
  deploy:
    name: deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@v1
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
